name: simworld
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - numpy[version='<2']
  - python=3.10
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - matplotlib
prefix: /home/dell/miniconda3/envs/simworld
