name: AnyGrasp
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40=hb3c18ed_4
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cmake=4.1.1=hc85cc9f_0
  - cuda-cccl=12.1.109=ha770c72_0
  - cuda-cccl-impl=2.0.1=ha770c72_1
  - cuda-cccl_linux-64=12.1.109=ha770c72_0
  - cuda-cudart=12.1.105=hd3aeb46_0
  - cuda-cudart-dev=12.1.105=hd3aeb46_0
  - cuda-cudart-dev_linux-64=12.1.105=h59595ed_0
  - cuda-cudart-static=12.1.105=hd3aeb46_0
  - cuda-cudart-static_linux-64=12.1.105=h59595ed_0
  - cuda-cudart_linux-64=12.1.105=h59595ed_0
  - cuda-driver-dev=12.1.105=hd3aeb46_0
  - cuda-driver-dev_linux-64=12.1.105=h59595ed_0
  - cuda-libraries-dev=12.1.1=ha770c72_0
  - cuda-nvcc=12.1.105=hcdd1206_1
  - cuda-nvcc-dev_linux-64=12.1.105=ha770c72_0
  - cuda-nvcc-impl=12.1.105=hd3aeb46_0
  - cuda-nvcc-tools=12.1.105=hd3aeb46_0
  - cuda-nvcc_linux-64=12.1.105=h8a487aa_1
  - cuda-nvrtc=12.1.105=hd3aeb46_0
  - cuda-nvrtc-dev=12.1.105=hd3aeb46_0
  - cuda-opencl=12.1.105=h59595ed_0
  - cuda-opencl-dev=12.1.105=h59595ed_0
  - cuda-profiler-api=12.1.105=ha770c72_0
  - cuda-version=12.1=h1d6eff3_3
  - gcc_impl_linux-64=11.4.0=h00c12a0_13
  - gcc_linux-64=11.4.0=ha077dfb_4
  - gxx_impl_linux-64=11.4.0=h634f3ee_13
  - gxx_linux-64=11.4.0=h35bfe5d_4
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=12.1.3.1=hd3aeb46_0
  - libcublas-dev=12.1.3.1=hd3aeb46_0
  - libcufft=11.0.2.54=hd3aeb46_0
  - libcufft-dev=11.0.2.54=hd3aeb46_0
  - libcufile=1.6.1.9=hd3aeb46_0
  - libcufile-dev=1.6.1.9=hd3aeb46_0
  - libcurand=10.3.2.106=hd3aeb46_0
  - libcurand-dev=10.3.2.106=hd3aeb46_0
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.4.5.107=hd3aeb46_0
  - libcusolver-dev=11.4.5.107=hd3aeb46_0
  - libcusparse=12.1.0.106=hd3aeb46_0
  - libcusparse-dev=12.1.0.106=hd3aeb46_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-devel_linux-64=11.4.0=h8f596e0_113
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=15.1.0=h767d61c_4
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnpp=12.1.0.40=hd3aeb46_0
  - libnpp-dev=12.1.0.40=hd3aeb46_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.1.105=hd3aeb46_0
  - libnvjitlink-dev=12.1.105=hd3aeb46_0
  - libnvjpeg=12.2.0.2=h59595ed_0
  - libnvjpeg-dev=12.2.0.2=ha770c72_0
  - libopenblas=0.3.29=ha39b09d_0
  - libsanitizer=11.4.0=h5763a12_13
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-devel_linux-64=11.4.0=h8f596e0_113
  - libstdcxx-ng=15.1.0=h4852527_4
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb03c661_1
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h7934f7d_0
  - ninja=1.13.1=h171cf75_0
  - nomkl=3.0=0
  - nvtx=0.2.13=py310h7c4b9e2_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - openblas-devel=0.3.29=ha39b09d_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openssl=3.5.2=h26f9b46_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=hd6af730_0_cpython
  - python_abi=3.10=8_cp310
  - readline=8.3=hc2a1206_0
  - rhash=1.4.6=hb9d3cd8_1
  - sqlite=3.50.4=hbc0de68_0
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - addict==2.4.0
      - autolab-core==1.1.1
      - autolab-perception==1.0.0
      - blinker==1.9.0
      - certifi==2025.8.3
      - click==8.2.1
      - colorlog==6.9.0
      - configargparse==1.7.1
      - cvxopt==1.3.2
      - cycler==0.12.1
      - dash==3.2.0
      - decorator==5.2.1
      - dill==0.4.0
      - fastjsonschema==2.21.2
      - ffmpeg-python==0.2.0
      - flask==3.1.2
      - fonttools==4.59.2
      - future==1.0.0
      - grasp-nms==1.0.2
      - graspnetapi==1.2.11
      - h5py==3.14.0
      - idna==3.10
      - itsdangerous==2.2.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - minkowskiengine==0.5.4
      - mpmath==1.3.0
      - multiprocess==0.70.18
      - narwhals==2.3.0
      - nbformat==5.10.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - open3d==0.19.0
      - packaging==25.0
      - pandas==2.3.2
      - pexpect==4.9.0
      - pillow==11.0.0
      - pip==22.2.2
      - plotly==6.3.0
      - pointnet2==0.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyquaternion==0.9.9
      - pyserial==3.5
      - pytz==2025.2
      - pywavefront==1.3.3
      - pyyaml==6.0.2
      - retrying==1.4.2
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.12
      - scikit-image==0.25.2
      - scikit-learn==1.1.3
      - scipy==1.15.3
      - setproctitle==1.3.6
      - setuptools==69.5.1
      - six==1.17.0
      - sympy==1.13.1
      - tifffile==2025.5.10
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - trimesh==4.8.0
      - triton==3.1.0
      - typing-extensions==4.12.2
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - zipp==3.23.0
prefix: /home/cindy/anaconda3/envs/AnyGrasp
